# Generated by Django 3.2.9 on 2022-05-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_userinfo_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='title',
            new_name='caption',
        ),
    ]
