# Generated by Django 3.2.9 on 2022-05-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_rename_title_department_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default=222, max_length=64, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=16, verbose_name='用户名'),
        ),
    ]
